# Generated by Django 5.2.10 on 2026-01-10 17:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users_Users',
            },
        ),
        migrations.CreateModel(
            name='SavedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_relevant', models.BooleanField(default=True)),
                ('from_stop_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_stop_in_the_time', to='tasks.stoptime')),
                ('to_stop_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_stop_in_the_time', to='tasks.stoptime')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'users_SavedTrips',
                'unique_together': {('user', 'trip')},
            },
        ),
        migrations.CreateModel(
            name='SavedTransit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_transits', to='tasks.stop')),
                ('to_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_transits', to='tasks.stop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'users_SavedTransits',
                'indexes': [models.Index(fields=['user'], name='users_Saved_user_id_aa0117_idx')],
                'unique_together': {('user', 'from_stop', 'to_stop')},
            },
        ),
    ]
