# Generated by Django 5.2.10 on 2026-01-11 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_finaltrip_set_unlogged'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinalTrip',
            new_name='CompleteTrip',
        ),
        migrations.AlterModelTable(
            name='completetrip',
            table='trips_CompleteTrips',
        ),
    ]
