# Generated by Django 5.2.10 on 2026-01-20 13:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_rename_finaltrip_completetrip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completetrip',
            name='stops',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8), size=None),
        ),
    ]
