# Generated by Django 5.2.10 on 2026-01-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tranfer',
            new_name='Transfer',
        ),
        migrations.RenameModel(
            old_name='TranferStaging',
            new_name='TransferStaging',
        ),
    ]
