# Generated by Django 5.2.10 on 2026-01-07 19:47

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('service_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('start_date', models.CharField(max_length=8)),
                ('end_date', models.CharField(max_length=8)),
                ('weekdays_avialability', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), size=7)),
            ],
            options={
                'db_table': 'common_Calendars',
            },
        ),
        migrations.CreateModel(
            name='CalendarStaging',
            fields=[
                ('service_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('start_date', models.CharField(max_length=8)),
                ('end_date', models.CharField(max_length=8)),
                ('weekdays_avialability', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), size=7)),
            ],
            options={
                'db_table': 'staging_Calendars',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('route_short_name', models.CharField(max_length=8)),
                ('route_long_name', models.CharField(max_length=128)),
                ('route_type', models.IntegerField(choices=[(2, 'Rail'), (3, 'Bus')])),
                ('route_color', models.CharField(max_length=6)),
                ('route_text_color', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'common_Routes',
            },
        ),
        migrations.CreateModel(
            name='RouteStaging',
            fields=[
                ('route_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('route_short_name', models.CharField(max_length=8)),
                ('route_long_name', models.CharField(max_length=128)),
                ('route_type', models.IntegerField(choices=[(2, 'Rail'), (3, 'Bus')])),
                ('route_color', models.CharField(max_length=6)),
                ('route_text_color', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'staging_Routes',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=128)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
            ],
            options={
                'db_table': 'common_Stops',
            },
        ),
        migrations.CreateModel(
            name='StopStaging',
            fields=[
                ('stop_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=128)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
            ],
            options={
                'db_table': 'staging_Stops',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('trip_headsign', models.CharField(max_length=128)),
                ('trip_short_name', models.CharField(max_length=32, null=True)),
                ('block_id', models.IntegerField(null=True)),
                ('plk_train_number', models.CharField(max_length=64)),
                ('carriages', models.CharField(max_length=128, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.route')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.calendar')),
            ],
            options={
                'db_table': 'common_Trips',
            },
        ),
        migrations.CreateModel(
            name='TranferStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.IntegerField(choices=[(1, 'Timed'), (4, 'In Seat')])),
                ('from_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='st_transfers_from', to='tasks.stop')),
                ('to_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='st_transfers_to', to='tasks.stop')),
                ('from_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='st_transfers_from', to='tasks.trip')),
                ('to_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='st_transfers_to', to='tasks.trip')),
            ],
            options={
                'db_table': 'staging_Transfers',
            },
        ),
        migrations.CreateModel(
            name='Tranfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.IntegerField(choices=[(1, 'Timed'), (4, 'In Seat')])),
                ('from_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='tasks.stop')),
                ('to_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='tasks.stop')),
                ('from_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='tasks.trip')),
                ('to_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='tasks.trip')),
            ],
            options={
                'db_table': 'common_Transfers',
            },
        ),
        migrations.CreateModel(
            name='TripStaging',
            fields=[
                ('trip_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('trip_headsign', models.CharField(max_length=128)),
                ('trip_short_name', models.CharField(max_length=32, null=True)),
                ('block_id', models.IntegerField(null=True)),
                ('plk_train_number', models.CharField(max_length=64)),
                ('carriages', models.CharField(max_length=128, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.route')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.calendar')),
            ],
            options={
                'db_table': 'staging_Trips',
            },
        ),
        migrations.CreateModel(
            name='StopTimeStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_sequence', models.IntegerField()),
                ('arrival_time', models.CharField(max_length=8)),
                ('departure_time', models.CharField(max_length=8)),
                ('platform', models.SmallIntegerField()),
                ('track', models.CharField(max_length=8)),
                ('fare_dist_m', models.IntegerField()),
                ('vehicle_kind', models.CharField(max_length=16)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.trip')),
            ],
            options={
                'db_table': 'staging_StopTimes',
                'unique_together': {('trip', 'stop_sequence')},
            },
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_sequence', models.IntegerField()),
                ('arrival_time', models.CharField(max_length=8)),
                ('departure_time', models.CharField(max_length=8)),
                ('platform', models.SmallIntegerField()),
                ('track', models.CharField(max_length=8)),
                ('fare_dist_m', models.IntegerField()),
                ('vehicle_kind', models.CharField(max_length=16)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.trip')),
            ],
            options={
                'db_table': 'common_StopTimes',
                'unique_together': {('trip', 'stop_sequence')},
            },
        ),
    ]
