# Generated by Django 5.2.10 on 2026-01-08 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoptimestaging',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.stopstaging'),
        ),
        migrations.AlterField(
            model_name='stoptimestaging',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tripstaging'),
        ),
        migrations.AlterField(
            model_name='tranferstaging',
            name='from_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='st_transfers_from', to='tasks.stopstaging'),
        ),
        migrations.AlterField(
            model_name='tranferstaging',
            name='from_trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='st_transfers_from', to='tasks.tripstaging'),
        ),
        migrations.AlterField(
            model_name='tranferstaging',
            name='to_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='st_transfers_to', to='tasks.stopstaging'),
        ),
        migrations.AlterField(
            model_name='tranferstaging',
            name='to_trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='st_transfers_to', to='tasks.tripstaging'),
        ),
        migrations.AlterField(
            model_name='tripstaging',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.routestaging'),
        ),
        migrations.AlterField(
            model_name='tripstaging',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.calendarstaging'),
        ),
    ]
