# Generated by Django 5.2.10 on 2026-01-08 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_stoptimestaging_stop_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='weekdays_avialability',
            new_name='weekdays_availability',
        ),
        migrations.RenameField(
            model_name='calendarstaging',
            old_name='weekdays_avialability',
            new_name='weekdays_availability',
        ),
    ]
