# Generated by Django 5.2.10 on 2026-01-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_weekdays_avialability_calendar_weekdays_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoptime',
            name='platform',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='track',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='stoptimestaging',
            name='platform',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='stoptimestaging',
            name='track',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
